### ISSUE TITLE
您好关于ACDC想请教您关于以下几个方面的问题

### ISSUE THREAD

**Issue by xiaokeaiyayaya** [mli0603/ACDC2017#1]
您好想请教您关于以下几个方面的问题
1.关于语言，我是用tensorflow，使用同样的unet模型结果和您差距很大，请问您在tensorflow上试验过吗？结果如何。
2.关于权重：请问the best weight of dice
loss is set to 0:1905; 0:9524; 1:9048 and 0:9524.这里的权重如何获得的？
3.比赛中的测试集您如何预测的，首先根据您的代码，随机剪切（256，256）大小的图像，但是比赛的测试集图像大小不固定，如果您随机剪切了，如果恢复到原来的图像呢？

**Comment by mli0603** [comment]
你好！
1. 我没有在tensorflow测试过，所以不确定模型在重新实现的过程中会不会有些许误差。你有尝试在pytorch重现吗？
2. 这个权重是取每一个分类出现的频率的倒数，也就是说出现频率更高的分类会得到一个更小的权重。
3. 测试集的处理方法和训练集类似。剪切的方法可以再augmentation的代码中找到（[链接](https://github.com/mli0603/ACDC2017/blob/master/code/augmentation.py#L174)），实现方法是在接近中心的地方随机剪切（256,256）的大小，然后再将语义分割的结果放回原位。

**Comment by xiaokeaiyayaya** [comment]
请问关于accuracy的计算：
 pred = torch.max(probas,dim=1)[1]
    pred_1_hot = torch.eye(num_class)[pred.squeeze(1)]
    pred_1_hot = pred_1_hot.permute(0, 3, 1, 2).float()
有点没明白，第一行是max，将channel变成一维，变为（B，1，H，W），然后后面接【1】这里啥意思，是B取第一个吗？
第二行创建单位阵，如果上面pred是（B，1，H，W），pred.squeeze(1)==》（B，H，W）
那么torch.eye(num_class)[pred.squeeze(1)]这里是做了什么呢？没明白

**Comment by mli0603** [comment]
loss的计算是用one hot encoding计算的。
1. [torch.max](https://pytorch.org/docs/stable/torch.html#torch.max)的documentation里面有说明，function会返回两个变量：一个是最大值，另一个是最大值对应的位置。因此`pred = torch.max(probas,dim=1)[1]`取的是最大值对应的位置，也就是对应的class。
2. 第二行是为了将得到的class变成one hot encoding。`pred.squeeze(1)`是将第二个dimension去除掉，得到`[B,H,W]`。`torch.eye(num_class)[pred.squeeze(1)]`就是通过indexing将对应的class变成one hot的过成，得到一个`[B,H,W,num_class]`的tensor。indexing的原理详见[链接](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#advanced-indexing)。
